apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment # deployment name
  labels:
    app.kubernetes.io/name: apache
    app: apache
spec:
  replicas: 1 # number of  Pods to run
  selector:
    matchLabels: # select list of PODS which are included into this deployment
      app: apache-pod-label
  template: # define Pod
    metadata:
      name: apache-pod # Pod name
      labels:
        app: apache-pod-label
    spec:
      volumes:
        - name: project-volume # project directory
          persistentVolumeClaim:
            claimName: project-pvc
        - name: httpd-config # configMap
          configMap:
            name: httpd-conf
            defaultMode: 0644
      containers: # list of Pod containers
        - name: apache-container
          image: httpd:2.4-alpine
          ports:
            - containerPort: 80 # port to expose
          volumeMounts:
            - name: project-volume
              mountPath: /var/www/html
            - name: httpd-config
              mountPath: /usr/local/apache2/conf/httpd.conf # to mount a file we have to point out this file ONLY
              subPath: httpd.conf
          envFrom:
            - configMapRef:
                name: variables
---
apiVersion: v1
kind: Service
metadata:
  name: apache
spec:
  type: NodePort
  selector:
    app: apache-pod-label
  ports:
    - protocol: TCP
      port: 80