apiVersion: v1
kind: PersistentVolume
metadata:
    name: project-pv
    labels:
        type: local
spec:
    storageClassName: manual # this value should match to PVC or omitted completely for if hostPath is default storageclass
    accessModes:
        - ReadWriteOnce # this is the only option available for hostPath
    volumeMode: Filesystem # default value. Possible values Filesystem (mount into a directory) and Block (mount as a block device)
    capacity:
        storage: 10Mi # The only capacity option available for volumes. Make storage just 10 Mib for teting purposes
    hostPath:
        path: /C/Users/roman/docker/phpapachemysql/htdocs  # path to volume (this trick works for Windows)
